---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mosi-agil.
--- DateTime: 19/04/18 12:26
---
-- This simulation creates ten groups of pedestrian, five of them in the main gate and another five in the back gate.
-- All groups walking with different speeds between 1-5 and with the destination at the different classrooms.
-- All they using the behavior FollowingPath
Scenario = {
    Scene="Faculty_1floor",
    CameraConfig = {
        location = { 91.36081, 25.665495, 67.48593 },
        rotation = { 90.0,0.0,0.0 },
        lookAt = { 0.0, -1.0, 0.0 }
    },
    AgentsDescriptions = {
        GotoClass1 = {
            behavior = "FollowingPath",
            Speed=4.0,
            AnimationSpeedReference = 4.0,
            RewriteParameter = {
                Path = "MainHall.Entrance,MainHall.Library,LobbyEventRoom.Hall,ClassesLobby.Class1,Class1"
            }
        },
        GotoClass2 = {
            behavior = "FollowingPath",
            Speed=4.0,
            AnimationSpeedReference = 4.0,
            RewriteParameter = {
                Path = "MainHall.Entrance,MainHall.Library,LobbyEventRoom.Hall,ClassesLobby.Class1,ClassesLobby.Class2,Class2"
            }
        },
        GotoClass3 = {
            behavior = "FollowingPath",
            Speed=4.0,
            AnimationSpeedReference = 4.0,
            RewriteParameter = {
                Path = "MainHall.Entrance,MainHall.Library,LobbyEventRoom.Hall,ClassesLobby.Class1,ClassesLobby.Class2,ClassesLobby.Class3,Class3"
            }
        },
        GotoClass4 = {
            behavior = "FollowingPath",
            Speed=4.0,
            AnimationSpeedReference = 4.0,
            RewriteParameter = {
                Path = "HallBackGate.Lobby,ClassesLobby.Class5,ClassesLobby.Class4,Class4"
            }
        },
        GotoClass5 = {
            behavior = "FollowingPath",
            Speed=4.0,
            AnimationSpeedReference = 4.0,
            RewriteParameter = {
                Path = "HallBackGate.Lobby,ClassesLobby.Class5,Class5"
            }
        },
        ExitClass1 = {
            behavior = "FollowingPath",
            Speed=4.0,
            AnimationSpeedReference = 4.0,
            RewriteParameter = {
                Path = "ClassesLobby.Class1,ElevatorsLobby,LobbyCafeteria,MainHall.Entrance,MainGate";
            }
        },
        ExitClass2 = {
            behavior = "FollowingPath",
            Speed=4.0,
            AnimationSpeedReference = 4.0,
            RewriteParameter = {
                Path = "ClassesLobby.Class2,ClassesLobby.Class1,LobbyEventRoom.Hall,MainHall.Library,MainHall.Entrance,MainGate";
            }
        },
        ExitClass3 = {
            behavior = "FollowingPath",
            Speed=4.0,
            AnimationSpeedReference = 4.0,
            RewriteParameter = {
                Path = "ClassesLobby.Class3,ClassesLobby.Class2,ClassesLobby.Class1,ElevatorsLobby,LobbyCafeteria,MainHall.Entrance,MainGate";
            }
        },
        ExitClass4 = {
            behavior = "FollowingPath",
            Speed=4.0,
            AnimationSpeedReference = 4.0,
            RewriteParameter = {
                Path = "ClassesLobby.Class4,ClassesLobby.Class5,HallBackGate.Lobby,BackGate";
            }
        },
        ExitClass5 = {
            behavior = "FollowingPath",
            Speed=4.0,
            AnimationSpeedReference = 4.0,
            RewriteParameter = {
                Path = "ClassesLobby.Class5,HallBackGate.Lobby,BackGate"
            }
        },


        Class1tToClass5 = {
            behavior = "FollowingPath",
            Speed=4.0,
            AnimationSpeedReference = 4.0,
            RewriteParameter = {
                Path = "ClassesLobby.Class1,ClassesLobby.Class2,ClassesLobby.Class3,ClassesLobby.Class4,Class5"
            }
        },
        Class5ToClass1 = {
            behavior = "FollowingPath",
            Speed=4.0,
            AnimationSpeedReference = 4.0,
            RewriteParameter = {
                Path = "ClassesLobby.Class4,ClassesLobby.Class3,ClassesLobby.Class2,ClassesLobby.Class1,Class1"
            }
        },
        Class2tToCaffeterie = {
            behavior = "FollowingPath",
            Speed=4.0,
            AnimationSpeedReference = 4.0,
            RewriteParameter = {
                Path = "ClassesLobby.Class2,ClassesLobby.Class1,ElevatorsLobby,LobbyCafeteria,CafeteriaHall,StudentsCafeteria"
            }
        },
        GoToEventRoom={
            behavior="FollowingPath",
            Speed=4.0,
            AnimationSpeedReference = 4.0,
            RewriteParameter = {
                Path = "MainHall.Entrance,MainHall.Library,LobbyEventRoom.Hall,LobbyEventRoom.EventRoom,EventRoom"
            }
        }
    }
}

Commands:

MassisLua.createHuman("GotoClass1", 15, "MainGate")
MassisLua.createHuman("GotoClass2", 15, "MainGate")
MassisLua.createHuman("GotoClass3", 15, "MainGate")
MassisLua.createHuman("GotoClass4", 15, "BackGate")
MassisLua.createHuman("GotoClass5", 15, "BackGate")
MassisLua.createHuman("ExitClass1", 15, "Class1")
MassisLua.createHuman("ExitClass2", 15, "Class2")
MassisLua.createHuman("ExitClass3", 15, "Class3")
MassisLua.createHuman("ExitClass4", 15, "Class4")
MassisLua.createHuman("ExitClass5", 15, "Class5")
MassisLua.createHuman("Class1tToClass5", 15, "Class1")
MassisLua.createHuman("Class5ToClass1", 15, "Class5")
MassisLua.createHuman("Class2tToCaffeterie", 20, "Class2")
MassisLua.createHuman("GoToEventRoom", 20, "MainGate")

