---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mosi-agil.
--- DateTime: 18/07/18 14:22
---
Scenario = {
    Scene="Faculty_1floor",
    CameraConfig = {
        location = {80.76, 60.47, 56.0},
        rotation = {90.0,0.0,0.0},
        lookAt = {80.76,60.47,56.0}
    },
    AgentsDescriptions = {
        Thief = {
            behavior = "Thief",
            tag = "Thief",
            Speed = 4.0,
            RewriteParameter = {
                TagToSearch = "Victims",
                PlaceListToRunAway = "MainGate,BackGate"
            },
            Components = {
                Personality = {
                    suspiciousFactor = 0.5
                }
            }
        },
        Victims01 = {
            behavior = "FollowingPathAgent",
            Speed = 2.0,
            tag = "Victims",
            RewriteParameter = {
                Path = "MainGate,LobbyEventRoom.Hall,ClassesLobby.Class1,ElevatorsLobby,CafeteriaHall",
                IsCircularPath = true,
                StoppingDistance=4
            }
        },
        Victims02 = {
            behavior = "FollowingPathAgent",
            Speed = 2.0,
            tag = "Victims",
            RewriteParameter = {
                Path = "CafeteriaHall,ElevatorsLobby,ClassesLobby.Class1,LobbyEventRoom.Hall,MainGate",
                IsCircularPath = true,
                StoppingDistance=4
            }
        },
        Security = {
            behavior = "Security",
            tag = "Security",
            Speed = 4.0,
            RewriteParameter = {
                PathToPatrol = "MainHall.Entrance,MainHall.Library,LobbyEventRoom.Hall",
                SuspuciousLevel = 0.7
            },
            Components = {
                Perception = {
                    visionAngle = 160.0,
                    visionSqrDisance = 100.0
                }
            }
        }
    }
}

Commands:

--MassisLua.createHumanDeferred("Thief",1,"MainGate",20)
MassisLua.createHuman("Victims01", 50, "MainGate")
MassisLua.createHuman("Victims02", 50, "CafeteriaHall")