---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mosi-agil.
--- DateTime: 27/07/18 12:39
---

Scenario = {
    Scene="tutorial",
    CameraConfig = {
        location = {347.0, 278.0, 161.0},
        rotation = {90.0,0.0,0.0},
        lookAt = {347.0,0.0,161.0}
    },
    AgentsDescriptions = {
        Crew = {
            behavior = "Crew",
            Speed = 3.0,
            tag = "Crew"
        },
        Rescuer = {
            behavior = "FollowingPathAgent",
            Speed = 2.0,
            tag = "Rescuer",
            RewriteParameter = {
                Path = "TLRoomCenter,TRRoomCenter,BRRoomCenter,BLRoomCenter",
                IsCircularPath = true,
                StoppingDistance=4
            }
        }
    }
}

Commands:


MassisLua.createHuman("Crew", 1, "TLRoomCenter")
MassisLua.createHuman("Crew", 1, "TRRoomCenter")
MassisLua.createHuman("Crew", 1, "BRRoomCenter")
MassisLua.createHuman("Crew", 1, "BLRoomCenter")
MassisLua.createHumanDeferred("Rescuer", 10, "TLRoomCenter", 5)
