---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mosi-agil.
--- DateTime: 8/06/18 17:11
---
Scenario = {
    Scene="Faculty_1floor",
    CameraConfig = {
        location = { 70.0, 100.0, 55.0 },
        rotation = { 90.0,0.0,0.0 },
        lookAt = { 0.0, -1.0, 0.0 }
    },
    AgentsDescriptions = {
        Agent01={
            behavior = "ArriveWaitLeave",
            SpeedMin = 1.0,
            SpeedMax = 5.0,
            AnimationSpeedReference = 4.0,
            RewriteParameter = {
                Path = "Class1",
                Time=2.0,
                PlaceListToRunAway="MainGate,BackGate"
            }
        }
    }
}

Commands:

MassisLua.createHuman("Agent01", 1, "MainGate")